---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-1
  labels:
    app: alpine-1
  annotations:
    networkservicemesh.io: kernel://ipam-policies/nsm-1
spec:
  containers:
  - name: alpine-1
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    env:
      - name: NSM_LOG_LEVEL
        value: INFO
    # simple `sleep` command would work
    # but we need `trap` to be able to delete pods quckly
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
