---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-2
  labels:
    app: alpine-2
  annotations:
    networkservicemesh.io: kernel://ipam-policies/nsm-2
spec:
  containers:
  - name: alpine-2
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    env:
      - name: NSM_LOG_LEVEL
        value: INFO
    # simple `sleep` command would work
    # but we need `trap` to be able to delete pods quckly
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
