---
apiVersion: v1
kind: Pod
metadata:
  name: nse-kernel-1
  labels:
    app: nse-kernel-1
    "spiffe.io/spiffe-id": "true"
spec:
  containers:
    - name: nse
      image: ghcr.io/networkservicemesh/ci/cmd-nse-icmp-responder:420c0b8
      imagePullPolicy: IfNotPresent
      env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NSM_NAME
          value: "$(POD_NAME)"
        - name: NSM_LOG_LEVEL
          value: TRACE
        - name: NSM_CONNECT_TO
          value: unix:///var/lib/networkservicemesh/nsm.io.sock
        - name: NSM_CIDR_PREFIX
          value: 172.16.1.100/31
        - name: NSM_SERVICE_NAMES
          value: "multiple-services-1"
        - name: NSM_REGISTER_SERVICE
          value: "false"
      volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: nsm-socket
          mountPath: /var/lib/networkservicemesh
          readOnly: true
      resources:
        requests:
          cpu: 100m
          memory: 40Mi
        limits:
          memory: 80Mi
          cpu: 200m
  volumes:
    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets
        type: Directory
    - name: nsm-socket
      hostPath:
        path: /var/lib/networkservicemesh
        type: DirectoryOrCreate
