---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
    spiffe.io/spiffe-id: "true"
spec:
  containers:
    - name: nsc
      image: ghcr.io/networkservicemesh/ci/cmd-nsc:c86914d
      imagePullPolicy: IfNotPresent
      env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_LOG_LEVEL
          value: TRACE
        - name: NSM_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NSM_NETWORK_SERVICES
          value: kernel://component-restart/nsm-1
        - name: NSM_MAX_TOKEN_LIFETIME
          value: "2m"
        - name: NSM_REQUEST_TIMEOUT
          value: "5s"
      volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: nsm-socket
          mountPath: /var/lib/networkservicemesh
          readOnly: true
      resources:
        limits:
          memory: 80Mi
          cpu: 200m
  volumes:
    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets
        type: Directory
    - name: nsm-socket
      hostPath:
        path: /var/lib/networkservicemesh
        type: DirectoryOrCreate
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - client
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nse-kernel
