---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-noop
  labels:
    app: nse-noop
spec:
  selector:
    matchLabels:
      app: nse-noop
  template:
    metadata:
      labels:
        app: nse-noop
        "spiffe.io/spiffe-id": "true"
    spec:
      hostNetwork: true
      containers:
        - name: nse
          image: ghcr.io/networkservicemesh/ci/cmd-nse-vfio:59a52aa
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_SERVICE_NAMES
              value: "pingpong: { addr: 0a:55:44:33:22:11 }"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm
              mountPath: /var/lib/networkservicemesh
          # We don't actually need SR-IOV resources for NSE, but we need to be sure that it is going to be deployed
          # on the correct node.
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 40Mi
              cpu: 200m
              # We expect SR-IOV forwarders on the nodes to be configured:
              # master - provides PCI functions targeted to the worker.domain/10G
              # worker - provides PCI functions targeted to the master.domain/10G
              master.domain/10G: 1

      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm
          hostPath:
            path: /var/lib/networkservicemesh
            type: Directory
