---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-k8s
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        "spiffe.io/spiffe-id": "true"
    spec:
      serviceAccountName: registry-k8s-sa
      containers:
        - image: ghcr.io/networkservicemesh/ci/cmd-registry-k8s:1365d74
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_LISTEN_ON
              value: tcp://:5002
            - name: NSM_PROXY_REGISTRY_URL
              value: nsmgr-proxy:5004
            - name: NSM_PPROF_ENABLED
              value: "true"
            - name: NSM_PPROF_LISTEN_ON
              value: "localhost:6060"
          imagePullPolicy: IfNotPresent
          name: registry
          ports:
            - containerPort: 5002
              hostPort: 5002
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 260Mi
              cpu: 200m
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
