---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse
  labels:
    app: nse
spec:
  selector:
    matchLabels:
      app: nse
  template:
    metadata:
      labels:
        app: nse
    spec:
      containers:
        - image: networkservicemeshci/cmd-nse-icmp-responder:bb7e6a46
          imagePullPolicy: IfNotPresent
          name: nse
          env:
            - name: NSE_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
