---
apiVersion: apps/v1
kind: Pod
metadata:
  # Limit the length of the name. Spire doesn't work with the length > 63
  name: nse-icmp-responder-{{ printf "%.39s"  (index .Labels "nodeName")}}pod
  labels:
    app: nse-icmp-responder
    "spiffe.io/spiffe-id": "true"
spec:
  nodeName: {{index .Labels "nodeName"}}
  restartPolicy: Never
  containers:
    - name: nse-icmp-responder
      image: ghcr.io/networkservicemesh/ci/cmd-nse-icmp-responder:99beb76
      imagePullPolicy: IfNotPresent
      env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NSM_CONNECT_TO
          value: unix:///var/lib/networkservicemesh/nsm.io.sock
        - name: NSM_CIDR_PREFIX
          value: 169.254.0.0/16
        - name: NSM_SERVICE_NAMES
          value: autoscale-icmp-responder
        - name: NSM_LABELS
          value: app:nse-icmp-responder
        - name: NSM_IDLE_TIMEOUT
          value: 15s
        - name: NSM_LOG_LEVEL
          value: TRACE
      volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: nsm-socket
          mountPath: /var/lib/networkservicemesh
          readOnly: true
      resources:
        limits:
          memory: 20Mi
          cpu: 100m
  volumes:
    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets
        type: Directory
    - name: nsm-socket
      hostPath:
        path: /var/lib/networkservicemesh
        type: DirectoryOrCreate
