---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-remote-vlan
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_CONNECT_TO
              value: "registry:5002"
            - name: NSM_SERVICES
              value: "finance-bridge { vlan: 100; via: gw1}"
            - name: NSM_CIDR_PREFIX
              value: 172.10.0.0/24,100:200::/64
            - name: NSM_MAX_TOKEN_LIFETIME
              value: "60s"
            - name: NSM_REGISTER_SERVICE
              value: "false"
