---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
  labels:
    app: nse-kernel
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_REGISTER_SERVICE
              value: "false"
            - name: NSM_SERVICE_NAMES
              value: "my-networkservice"
