---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  annotations:
    networkservicemesh.io: kernel://dns/nsm-1
  labels:
    app: dnsutils
    "spiffe.io/spiffe-id": "true"
spec:
  containers:
  - name: dnsutils
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nse-kernel
