---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-k8s
spec:
  template:
    spec:
      containers:
        - name: admission-webhook-k8s
          env:
            - name: NSM_ENVS
              value: NSM_LOG_LEVEL=INFO,NSM_LOCAL_DNS_SERVER_ENABLED=False
