---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

resources:
- spire.spiffe.io_clusterspiffeids.yaml
- spire.spiffe.io_clusterfederatedtrustdomains.yaml
- spire-namespace.yaml
- agent-account.yaml
- agent-cluster-role.yaml
- agent-daemonset.yaml
- role.yaml
- role_binding.yaml
- server-account.yaml
- server-cluster-role.yaml
- server-service.yaml
- server-statefulset.yaml
- spire-bundle-configmap.yaml
- server-role.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- spire-controller-manager-webhook.yaml
