---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NAME
              value: "$(POD_NAME)@my.cluster3"
            - name: NSM_CIDR_PREFIX
              value: 172.16.1.2/31
            - name: NSM_SERVICE_NAMES
              value: floating-kernel2ip2kernel@my.cluster3
            - name: NSM_PAYLOAD
              value: IP
            - name: NSM_REGISTER_SERVICE
              value: "false"
