---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  labels:
    app: dnsutils
  annotations:
    networkservicemesh.io: kernel://floating-dns@my.cluster3/nsm-1
spec:
  containers:
    - name: dnsutils
      image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
      imagePullPolicy: IfNotPresent
      stdin: true
      tty: true
