---
apiVersion: v1
kind: Pod
metadata:
  name: nse-vl3-vpp-2
  annotations:
    spiffe.io/federatesWith: nsm.cluster1,nsm.cluster3
  labels:
    app: nse-vl3-vpp
    "spiffe.io/spiffe-id": "true"
spec:
  containers:
    - name: nse
      image: ghcr.io/networkservicemesh/ci/cmd-nse-vl3-vpp:3210a43
      imagePullPolicy: IfNotPresent
      env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_NAME
          value: "nse-vl3-vpp-2@my.cluster3"
        - name: NSM_REGISTER_SERVICE
          value: "false"
        - name: NSM_SERVICE_NAMES
          value: "my-interdomain-vl3-network@my.cluster3"
        - name: NSM_PREFIX_SERVER_URL
          value: "tcp://vl3-ipam.nsm-system.my.cluster3:5006"
        - name: NSM_LOG_LEVEL
          value: TRACE
      volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: nsm-socket
          mountPath: /var/lib/networkservicemesh
          readOnly: true
      resources:
        requests:
          cpu: 150m
        limits:
          memory: 400Mi
          cpu: 500m
  volumes:
    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets
        type: Directory
    - name: nsm-socket
      hostPath:
        path: /var/lib/networkservicemesh
        type: DirectoryOrCreate
