---
apiVersion: v1
kind: Service
metadata:
  name: vl3-ipam
spec:
  selector:
    app: vl3-ipam
  ports:
    - name: vl3-ipam
      protocol: TCP
      port: 5006
      targetPort: 5006
  type: ClusterIP
