---
apiVersion: v1
kind: Service
metadata:
  name: greeting
  labels:
    app: greeting
    service: greeting
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: greeting
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting-sa
  labels:
    account: greeting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    app: greeting
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      serviceAccountName: greeting-sa
      containers:
      - name: server
        image: hashicorp/http-echo:alpine
        args:
          - -text="hello world from linkerd"
          - -listen=:9080
        ports:
          - containerPort: 9080
            name: http
---
