---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-3
  labels:
    app: alpine-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine-3
  template:
    metadata:
      labels:
        app: alpine-3
      annotations:
        networkservicemesh.io: kernel://green-bridge.ns-kernel2vlan-multins-2/nsm-1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - alpine-3
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: alpine
          image: alpine:3.15.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
