---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: nsm-workloads
spec:
  spiffeIDTemplate: "spiffe://nsm.cluster1/ns/{{.PodMeta.Namespace}}/pod/{{.PodMeta.Name}}"
  podSelector:
    matchLabels:
      "spiffe.io/spiffe-id": "true"
  federatesWith: ["nsm.cluster2", "nsm.cluster3"]
