---
apiVersion: networkservicemesh.io/v1
kind: NetworkService
metadata:
  name: nsm-linkerd
  namespace: ns-nsm-linkerd
spec:
  payload: IP
  matches:
    - source_selector:
      fallthrough: true
      routes:
        - destination_selector:
            podName: "{{ .podName }}"
    - source_selector:
      routes:
        - destination_selector:
            any: "true"
