---
apiVersion: v1
kind: Pod
metadata:
  name: scaled-nse-vl3-vpp-2
  annotations:
    spiffe.io/federatesWith: nsm.cluster1,nsm.cluster3
  labels:
    app: nse-vl3-vpp
    "spiffe.io/spiffe-id": "true"
spec:
  nodeName: '{{index .Labels "nodeName"}}'
  restartPolicy: Never
  containers:
    - name: nse
      image: ghcr.io/networkservicemesh/ci/cmd-nse-vl3-vpp:da420ce
      imagePullPolicy: IfNotPresent
      env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_NAME
          value: "scaled-nse-vl3-vpp-2@my.cluster3"
        - name: NSM_SERVICE_NAMES
          value: "autoscale-interdomain-vl3-network@my.cluster3"
        - name: NSM_REGISTER_SERVICE
          value: "false"
        - name: NSM_LABELS
          value: "app:nse-vl3-vpp,capability:vl3"
        - name: NSM_REQUEST_LABELS
          value: capability:vl3
        - name: NSM_PREFIX_SERVER_URL
          value: "tcp://vl3-ipam.nsm-system.my.cluster3:5006"
        - name: NSM_IDLE_TIMEOUT
          value: 15s
        - name: NSM_LOG_LEVEL
          value: TRACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: nsm-socket
          mountPath: /var/lib/networkservicemesh
          readOnly: true
      resources:
        requests:
          cpu: 150m
        limits:
          memory: 400Mi
          cpu: 500m
  volumes:
    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets
        type: Directory
    - name: nsm-socket
      hostPath:
        path: /var/lib/networkservicemesh
        type: DirectoryOrCreate
