---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-vl3-vpp
  labels:
    app: nse-vl3-vpp
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_SERVICE_NAMES
              value: "vl3-nse-death"
            - name: NSM_REGISTER_SERVICE
              value: "false"
